### PR TITLE
Added_Callback_function

### PR DESCRIPTION
**Pull request by ishan-chaudhary**
Added Callback Function Example

### CODE REVIEW

**Comment by kshitij86** [comment]
@ishan-chaudhary the code example looks great! Just put the `callback.js` directly into the `src` folder and remove the `examples` folder.

**Comment by ishan-chaudhary** [comment]
done

**Comment by kshitij86** [comment]
Fixes #10

**Comment by kshitij86** [comment]
@ishan-chaudhary  Thanks for your contribution! Don't forget to star the repository and open any new issues you feel are relevant.
Happy Hacktoberfest !

**Pull request merged**
